### ISSUE TITLE
post to APIGATEWAY

### ISSUE THREAD

**Issue by jgmurray23** [kndt84/aws-api-gateway-client#105]
Hi - is it possible to use the library to POST and aws api gateway endpoint with node?

If I do this:
 let resp = await apigClient.invokeApi(pathParamaters, pathTemplate, 'POST' , {}, body  )

I get get back: 

'The request signature we calculated does not match the signature you provided.....

If I do this:

 let resp = await apigClient.invokeApi(pathParamaters, pathTemplate, 'POST' , {}   )

The call succeeds with a 200 - but the body is empty and my function needs to pass data in the body to Lambda event

What am I doing wrong?

Thanks for any help!

**Comment by coolarm** [comment]
Ran into the same issue. All POST/PATCH/PUT requests with `body` are currently affected. I believe it is from a change in dependency Axios over [here](https://github.com/axios/axios/blob/master/lib/core/mergeConfig.js#L18). Axios is currently expecting that `url`, `method` and `data ` will be fetched from the parameters passed to the request method of the Axios client rather than be passed at client instantiation. I can attempt a pull request to get this fixed. For most use cases, v0.2.17 should do the job since it depends on an earlier compatible version of Axios.

**Comment by coolarm** [comment]
Looks like a commit has been made to address this over [here](https://github.com/kndt84/aws-api-gateway-client/commit/1a2f53027b5292a082aeab8b7926007b3b82686a). @willvincent @kndt84 Do you have a plan for when this will be released? Thanks!

**Comment by willvincent** [comment]
Well, yeah I made that pull request, and it was merged, but I don't maintain the package nor have the ability to do a release :)

**Comment by jgmurray23** [comment]
Thanks to you both, I'm using 0.2.17 for now which solved my problem - but I will test the next release whenever it appears.
