### ISSUE TITLE
Support for custom headers

### ISSUE THREAD

**Issue by marcelpanse** [kndt84/aws-api-gateway-client#59]
I'm using a combination of Auth0 with an API-gateway custom authenticator. In this situation you need to send an authorization header with a Bearer idToken. 

Currently, I don't see a way to send this header. I think it could be solved relatively easy by allowing a new field 'customHeaders' in the config and passing that to axios in the simpleHttpClient.js. 

I can make a fork and make a PR. 

Idea's?

**Comment by kndt84** [comment]
I will merge the PR after removing the binary file.

**Comment by jchen0022** [comment]
Hi, I was wondering if this change is working? I currently have code that gets the configuration:

function getConfig() {
    return {
        "invokeUrl": "https://xxxxxx.execute-api.us-east-1.amazonaws.com",
        "region": "us-east-1",
        "accessKey": accessKey,
        "secretKey": secretKey,
        "apiKey": userProfile.apiKey,
        "headers": {
            "custom-token": customToken
        }
    };
}

and makes the api call like this:
apigClient.invokeApi(additionalParams, orderingTemplate, method, {}, {});

But the gateway isn't able to acquire the custom-token from the header. Does anyone know why that might be the case, or am I using this customHeader incorrectly? Thanks!

**Comment by marcelpanse** [comment]
@jchen0022, it is working and I'm using it in production.
You should be able to see the header when you inspect the request in your browser and see if it is sent. If it is, the lib works fine and the problem is in your API Gateway configuration.

**Comment by jchen0022** [comment]
I'm currently running this code on a lambda function; do you know how to inspect the request programmatically? It doesn't seem to appear in the request that is echoed back in the gateway response, which leads me to think it isn't sent in the request. Hmmm really strange. I ended up getting my POST request to work using aws4 + axios, using https://medium.com/@joshua.a.kahn/calling-amazon-api-gateway-authenticated-methods-with-axios-and-aws4-6eeda1aa8696 as a reference in case others come across this, but this module seems so much easier/cleaner to use, so if you think you might know what's up, I'd really appreciate it. Otherwise, it's not a big deal, and thanks for the response anyways!

**Comment by WagdySamih** [comment]
I am running into the same issue 
```
  var apigClient = apigClientFactory.newClient({
    invokeUrl: eventsUrl,
    accessKey: accessKey,
    secretKey: secretKey,
    sessionToken: sessionToken,
    headers: {
      "custom-token": "customToken",
    },
    region: "eu-west-2",
    systemClockOffset: 0,
    retries: 4,
    retryCondition: (err) => {
      return err.response && err.response.status === 500;
    },
  });
  
  apigClient.invokeApi({}, path, method, {}, body)
```
But this doesn't show anything in my headers tab in developers tools

is there any solution to solve this and send a custom header in the client config instead of going through every API call?
